ventZl/cmrx

- ld/genlink-cmsis.py
Genlink script was written using Python 2 details of handling input and output which are incompatible with Python 3. Script has been updated and Python 2 compatibility has been dropped as Python 2 is EOLed for long time now.
> Fix genlink script to run with Python 3

- CMakeLists.txt
- include/cmrx/os/arch/static.h
- man/02_overview.md
- src/os/CMakeLists.txt
- src/os/arch/arm/CMakeLists.txt
- src/os/kernel/CMakeLists.txt
- testsuite/CMakeLists.txt
The previous arrangement with `os` and `cmrx_arch` libraries had issues during linking while both portions were refering to each other. That confused the linker.
Due to the strong coupling of these two portions - CMRX may be a microkernel but this microkernel is a monolith internally - it is better to simply put everything into one single library.
> Put all the kernel source into single library

- cmake/testing.cmake
- testsuite/debug.gdb
- testsuite/gdb.sh
The old approach was to launch OpenOCD in pipe mode with every test. This is quite slow and some probes are not that stable so sustain this. Tests then time out randomly. New approach is to launch OOCD when first test is launched and OpenOCD is not running yet and then to reuse that instance of OpenOCD.
> Use persistent OpenOCD instead of launching it with each test

- quirks/CMakeLists.txt
- quirks/README.md
- quirks/pico-sdk/CMakeLists.txt
- quirks/pico-sdk/README.md
- quirks/pico-sdk/cmrx_isrs.c
- quirks/pico-sdk/crt0.S
Add quirk, which patches pico-sdk to make it suitable to boot bare CMRX kernel.
All ISRs are defined inside the CMRX kernel handler as weak symbols. This way anyone who needs to hook any ISR can do that from within application library with no issues. The application has to be linked before the CMRX kernel gets linked.
> Add pico-sdk quirk

- include/cmrx/os/arch/context.h
- include/cmrx/os/arch/sched.h
- include/cmrx/os/context.h
- include/cmrx/os/runtime.h
- include/cmrx/os/sched.h
- src/os/arch/arm/pendsv.c
- src/os/kernel/CMakeLists.txt
- src/os/kernel/context.c
- src/os/kernel/isr.c
- src/os/kernel/sched.c
Currently the code performing context switch resides in platform support code even if most of it is rather generic and independent on actual platform. The code is split into two parts.
The generic part is moved out into the platform independent part of the kernel. This portion determines pointers to old and new thread and process. It the fills context switch structure and requests context switch.
The platform support part now contains only the heavy lifting part of the code which actually performs the switch.
As a part of this refactor, context switch context has been collected into one structure, instead of many free-standing variables. Just a little housekeeping, no real impact on functionality. Some unused variables have been removed from the context as they were either redundant or …
> Make context switch code portable

- src/os/arch/testing/pendsv.c
- src/os/kernel/context.c
Context switching stub is not needed anymore in testing port as the code is now generic and part of the kernel even in unit testing build.
Remove it and create dummy context switch request function that does the mock stuff and pretends that the context switch actually happened.
> Update testing "port" to reflect new switching code

- include/cmrx/arch/arm/cmsis/arch/sysenter.h
- src/extra/systick.c
- src/os/arch/arm/pendsv.c
- src/os/arch/arm/syscall.c
Service handlers that don't do special register handling (such as PendSV) were not marked as interrupts, so the compiler did not generate proper prologue and epilogue. This could lead to the corruption of register content if these handlers were executed.
The default CMSIS implementation of SysTick enable routine also does one poorly documented action: it changes the priority of SysTick handler to very low one. This caused that thread switches which were induced by the SysTick (such as round robin thread switching, or threads being resumed from sleep) experienced corrupted register status.
This was due to the PendSV handler preempting SysTick handler rather than being chained after it. The PendSV thus restored registers at the wrong time, causing thread just resumed to crash sooner or …
> Fix bugs in kernel that cause thread register corruption.

- include/cmrx/os/runtime.h
- src/os/kernel/isr.c
This commit performs a refactor of kernel code to use pointers to structures in arrays rather than indexing the array item again and again.
Repeating indexing coding pattern causes that GCC sometimes emits suboptimal and very bulky code.
Items in thread control block were reordered to allow for better packing and less RAM consuption by the kernel.
These changes cause the kernel to be almost 2kB smaller on ARMv6M machine than before. Current fully featured kernel compiles at around 5.5kB. Previously similar build was around 7.5kB.
> Use pointers to structures instead of direct access

- include/cmrx/os/runtime.h
This field will store the information on which core the thread is part of the work queue.
> Add core_id field into thread control block.

- cmake/options.cmake
- conf/kernel.h
- src/os/kernel/sched.c
Up until now stack size has been fixed at 1kB per thread which may not be enough for certain tasks. Make stack size configurable via CMakeLists. Other kernel configuration options also made configurable via CMakeLists.
> Make stack size compile-time configurable

- include/cmrx/defines.h
- include/cmrx/ipc/notify.h
- src/os/kernel/notify.c
- src/os/kernel/notify.h
If multiple pending notifications are emitted for the same object then these are collated into one pending entry. This entry now has a counter which records how many pending notifications there are. If count falls to zero then the entry in the table is freed-up.
This makes use of queues with vastly different processing speed at either end practical. Previously queues that have send bursts could bog the notification buffer causing kernel to panic.
notify_object() can now return E_OUT_OF_NOTIFICATIONS if too many pending notifications are on the fly.
> Collate multiple pending notifications into one entry

- src/os/arch/arm/cmsis/arch/scb.h
- src/os/arch/arm/cortex.c
- src/os/arch/arm/sanitize.c
- src/os/arch/testing/pendsv.c
- src/os/kernel/arch/context.h
- src/os/kernel/context.c
- src/os/kernel/notify.c
- src/os/kernel/sanitize.h
- src/os/kernel/sched.c
- src/os/kernel/tests/os_notify_wait_object.c
1.  Fix scheduler corruption due to nested PendSV schedule
There is a brief moment during which PendSV handler executes when
interrupts are not disabled yet. As the PendSV is the lowest priority
handler in the system, it may happen that it gets preempted by some
other interrupt handler.
This interrupt handler can issue isr_notify_object() or isr_kill()
effectively causing sched_yield() being executed. If that happens,
thread switch is planned by requesting PendSV to be called.
While we already are executing PendSV handler, this causes PendSV being
scheduled twice. This is usually not what you want.
The fix here clears PendSV request still existing just before PendSV is
going to return. These are spurious requests made in between PendSV
handler being scheduled by CPU and disabling …
> Fix scheduler corruptions

- include/cmrx/ipc/mutex.h
- src/lib/arch/arm/mutex.c
Mutex unlock code ignored the fact that STREX may fail and did not perform mutex unlocking in loop. Instead, upon first failure it simply reported that mutex unlocking failed.
Now the mutex unlocking performs loop until the lock is unlocked.
Unlike locking, which can fail simply because mutex is held by someone else, STREX performed during unlocking should normally fail only due to how load/store-exclusive are designed. Thus another round of unlocking is tried immediately without yielding the CPU.
Removed hand-written assembly implementation of futex locking/unlocking. Replaced by C code using instrinsics for STREX and LDREX.
> Fix mutex unlock code, drop hand-written assembly

- cmake/options.cmake
- conf/kernel.h
- include/cmrx/sys/trace.h
- src/os/kernel/CMakeLists.txt
- src/os/kernel/trace.c
- src/os/kernel/trace.h
Implement platform-agnostic tracing infrastructure that allows tracing various events around the kernel. Remaining unused RAM can be used as a trace buffer and trace events can be placed into code.
> Kernel tracing infrastructure

- src/lib/arch/arm/mutex.c
`success`  have to be initialized to `FUTEX_FAILURE` before returning it.
> fix __futex_fast_lock: success used uninitialized

- include/cmrx/ipc/mutex.h
`ldrex/strex` supports only one addressing mode - register.
Thus, if the state is not first member, compiler have to emit extra instruction to materialize address of `futex->state` in a register, which in turn increases register pressure and lead to less efficient code generated for `__futex_*` primitives.
> reorder futex_t entries for better optimization

- src/lib/arch/arm/mutex.c
At the moment `state` declared as `uint8_t` which forces compiler to truncate it explicitly after load or decrement operations. Truncation is unnecessary because strexb does implicit truncation.
> __futex_fast_unlock: avoid redundant truncations to uint8_t

- .clang-tidy
- CMakeLists.txt
- cmake/CMRX.cmake
- cmake/clang-tidy.cmake
- cmake/options.cmake
This adds `apply_clang_tidy()` CMake command which allows seamless application of clang-tidy to any target. This relies on compile-commands.json being available in the root directory, so this option is turned on in the main CMakeLists.txt of the CMRX.
Clang-tidy is enabled by default if clang-tidy executable is found. It can be disabled by setting CMRX_CLANG_TIDY option to false.
Clang-tidy can be invoked by running the `clang-tidy` target. This is not done automatically during the build for two reasons: 1) clang-tidy is not particularly fast if many checks are enabled 2) currently it reports some weird errors (such as missing system
headers)
> Integrate clang-tidy

- src/os/arch/arm/cmsis/arch/cortex.h
There's no need to specify r4-r11 as clobbers.
Actually clobbering forces compiler to wrap these asm routines into push {r4-r11} ... pop {r4-r11} which results in 3x data to be loaded from/stored into memory.
NB: I didn't test the change actually.
> save/load_context: avoid redundant activities

- src/os/kernel/notify.c
- src/os/kernel/txn.c
Notification engine: clang-tidy pointed out that some transaction initializations are never used. It turns out that the whole code of os_initialize_writable_object() is ineffective in terms of creating too many transactions.
This function is not extremely performance-critical as of now, but getting rid of unnecessary transaction creation helps.
Also, remove unused header include in transaction code.
> Kernel: fix some clang-tidy warnings

- .github/workflows/stm32h7-build.yml
The goal of this action is to perform a build of the latest CMRX tree on top of CubeMX-generated project to verify that the build is not broken.
> GH Action for STM32H7 integration build

- ld/checkapp.sh
I added a regex to match the start and end of the word so that inputs with prefixes/suffixes are handled correctly
> Fix: Checkapp.sh does not decode application name completely #59

- src/os/arch/arm/cmsis/arch/cortex.h
Particular piece of x86-ish looking assembly in operating system shutdown routine is not much compatible with ARM v6M assembly as Thumb1 instructions don't like long immediates.
The piece of assembly has been rewritten to use LDR instead of MOV to load these immediates from PC-relative location in flash.
> Fix build break on ARM v6M

- include/cmrx/defines.h
- include/cmrx/ipc/notify.h
- include/extra/queue_server/queue.h
- src/extra/queue_server/queue.c
- src/extra/queue_server/tests/test_queue_server.c
- src/os/kernel/isr.c
- src/os/kernel/notify.c
- src/os/kernel/notify.h
- src/os/kernel/sched.c
- src/os/kernel/tests/os_notify_wait_object.c
- src/os/kernel/timer.c
- src/os/kernel/timer.h
Wait for object syscall did contain timeout argument but up until now the call returned E_NOTAVAIL if timeout was any value different than zero.
Now timeout value can be specified in the call to wait, which will configure timer that aborts the wait for notification and returns E_TIMEOUT instead.
Substantial rework of the notification framework is part of this change as the actual handling of what happens when any notification arrives is up on the callback now. This made the callback a mandatory part of the framework unlike until now, callback might not be provided.
> Wait for object: implement timeouts

- include/cmrx/cmrx.h
- src/lib/std.c
A lot of code needs to compare timestamps. 32-bit microsecond timestamps wrap around about every hour and something. This function calculates distance between "older" and "newer" timestamp eliminating the effect of wraparounds.
Just an utility function so this piece of code doesn't have to be written again and again.
> Add library function to compare timestamps

- include/cmrx/ipc/rpc.h
Provide macro to perform typecast if and only if source and destination type are compatible regarding RPC interface. Useful for cases where type erasure of service type is needed while retaining compile-time type safety of RPC interface.
> RPC: Add interface cast

- include/cmrx/util.h
Added version of CONTAINER_OF macro that traverses up the data model.
This will allow us to avoid having back-pointers in various data structures.
> Add CONTAINER_OF macro

- include/extra/queue_server/queue.h
- src/extra/queue_server/tests/test_queue_server.c
The old behavior of STATIC_QUEUE macro was to define a variable. This is all nice and compact, but scales poorly if you need to access the queue from more than one compilation unit.
Thus this macro has been changed to macro STATIC_QUEUE_T which declares a type instead of variable. Thus the variable has to be defined by the developer.
The advantage of this approach is that you can declare the queue type in a header and then define / extern variables as needed in modules.
This is a breaking change for all the code which was already relying on STATIC_QUEUE.
In order to reveal such code early, we don't provide macro for backwards compatibility.
> Fix/Change: STATIC_QUEUE declares type rather than variable

- src/os/kernel/notify.c
- src/os/kernel/notify.h
- src/os/kernel/runtime.h
- src/os/kernel/sched.c
- src/os/kernel/sched.h
- src/os/kernel/tests/os_notify_wait_object.c
- src/os/kernel/timer.c
- src/os/kernel/timer.h
This commit fixes multiple places where transactions were either not used, or were used incorrectly. By incorrect use of transaction, it is meant that nested transaction commits were executed.
CMRX kernel transaction subsystem does *NOT* support nested transactions so this behavior caused any outer transaction to run unprotected. These two effects combined caused problems in wait_for_object() with timeout defined where in certain cases it could happen that the notification has been delivered *just* before the wait would time out. This led to crash inside the kernel.
This fix has a nature of hotfix. It was decided to rework the internals of the kernel to support "object methods" approach. There the architecture of who is responsible for creating transactions should be cleaner leading to …
> Hotfix: Fix wrong/missing use of transactions in kernel

- src/os/kernel/sched.c
Kernel has statically pre-allocated process table that cannot be resized in runtime. If there are too many applications/processes in the image, kernel would not create entries for some of them and threads belonging to these processes would fail at runtime due to no MPU configuration existing.
This adds assert into _os_start() that will stop kernel initialization if this situation happens.
> Kernel: Fail if too many processes are declared

- src/os/arch/arm/cmsis/arch/cortex.h
- src/os/arch/arm/cmsis/arch/runtime.h
- src/os/arch/arm/cortex.c
- src/os/arch/arm/mpu.c
- src/os/arch/arm/rpc.c
- src/os/arch/arm/runtime.c
- src/os/arch/arm/signal.c
GCC 14 is more strict than GCC 12 used to be. Some stuff we did is not tolerated anymore. Patch up these items and clean the source code a bit given the output from clang-tidy.
> Fix GCC 14 compilation errors

- .github/workflows/clang_tidy.yml
- cmake/clang-tidy.cmake
- testing/clang-tidy/CMakeLists.txt
- testing/clang-tidy/README.md
- testing/clang-tidy/mock/README.md
- testing/clang-tidy/mock/cmsis/cortex-m0+.ld
- testing/clang-tidy/mock/cmsis/cortex-m3.ld
- testing/clang-tidy/mock/cmsis/cortex-m4f.ld
- testing/clang-tidy/mock/cmsis/include/cortex-m0+.h
- testing/clang-tidy/mock/cmsis/include/cortex-m3.h
- testing/clang-tidy/mock/cmsis/include/cortex-m4f.h
- testing/clang-tidy/mock/cmsis/include/cortex.h
Add GitHub Action that creates three dummy builds of CMRX kernel for ARMv6M, ARMv7M and ARMv7M-F platforms and then launches clang-tidy on them.
Clang-tidy CMake module was augmented to provide additional include path so that standard library includes are found by clang-tidy.
Small barebone project and mocked CMSIS headers were creates so that these builds are syntactically correct and clang-tidy can do realistic reasoning on the code.
> Automation: Run clang-tidy automatically on commit / push

- src/extra/queue_server/queue.c
- src/extra/queue_server/tests/test_queue_server.c
If queues are larger than originally supported 256 bytes then code that reads and writes queues would occasionally corrupt both cursor positions and queue content.
This code changes internal cursor type from uint8_t to unsigned.
> Fix: Buffer cursor corruption for queues > 256 bytes

- CMakeLists.txt
- cmake/gcov.cmake
- cmake/unit_test_build.cmake
- src/extra/queue_server/CMakeLists.txt
- src/os/kernel/CMakeLists.txt
If production components (now the portable part of the OS kernel and the queue library) are build for testing purposes then these components are build with code coverage instrumentation turned on. All targets are linked with libgcov and when these tests are ran then coverage report is generated.
HTML version of the report can be generated using `coverage` target that is added to the build.
NB: Current test coverage is roughly 74% of kernel and 98% of queue server.
> Add coverage reporting for tests

- src/os/arch/arm/cmsis/arch/cortex.h
First executed thread is entered using software process that emulates ISR return. This is done in order to avoid having different setup for first thread and other threads.
The assembly routine which performed this "ISR return" was broken and popped register values from stack in wrong order. This caused that value which should end up in R0 (1st argument to the entry point) ended up somewhere else.
This caused the thread entry point function to work with random value instead of specified argument if and only if it was the thread that was the first to start. It did not happen if thread was first started via thread switcher.
> Fix: Thread entrypoint argument is invalid for booted thread
